In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
from numpy import concatenate
from pandas import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from tensorflow import keras
import tensorflow as tf
import time as t

In [25]:
w=32

In [26]:
dataFromSensors=np.load("DataWithLabels/dataFromSensors_"+str(w)+".npy")

In [27]:
np.info(dataFromSensors)

class:  ndarray
shape:  (475305, 32, 16)
strides:  (4096, 128, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f8e30700000
byteorder:  little
byteswap:  False
type: float64


In [28]:
my_array =dataFromSensors[:1]
np.set_printoptions(threshold=np.inf)
np.set_printoptions(linewidth=np.inf)
np.set_printoptions(suppress=True)


In [29]:
print(my_array)


[[[0.         0.49157834 0.86486486 0.40034662 0.40213523 0.02145491 0.00307325 0.50816583 0.32602568 0.54202192 0.3442623  0.93694444 0.04504505 0.80035651 0.02466828 0.00174415]
  [0.         0.49215751 0.86486486 0.40034662 0.40213523 0.02656721 0.00375619 0.50722362 0.32633887 0.54202192 0.39344262 0.93833333 0.04504505 0.80035651 0.03004879 0.00207956]
  [0.         0.49206274 0.86486486 0.40034662 0.40213523 0.01969494 0.00273177 0.50942211 0.32602568 0.5408039  0.44262295 0.93833333 0.04504505 0.80035651 0.02266199 0.00160998]
  [0.         0.49188372 0.86486486 0.40034662 0.40391459 0.02732149 0.00392693 0.50753769 0.32633887 0.53958587 0.41803279 0.92527778 0.04954955 0.80035651 0.03064156 0.00221373]
  [0.         0.49244183 0.86486486 0.40034662 0.40213523 0.02388535 0.00341472 0.50659548 0.32602568 0.53714982 0.40163934 0.93027778 0.04954955 0.80035651 0.02708495 0.00194539]
  [0.         0.49212066 0.86486486 0.39688042 0.40213523 0.02623198 0.00375619 0.50439698 0.3263388

In [31]:
labels=np.load("DataWithLabels/labels_"+str(w)+".npy")
print(labels[:1])

[0.]
